from typing import List, Set, Dict, Any
import dspy
import chromadb
from chromadb.api import ClientAPI
from chromadb.api.models.Collection import Collection
import bm25s
import pprint

ollama_qwen: dspy.LM = dspy.LM(
    model="ollama/qwen3:0.6b", api_base="http://localhost:11434", api_key="none"
)
dspy.configure(lm=ollama_qwen)

chroma_client: ClientAPI = chromadb.PersistentClient(path="./my_local_chromadb")
collection: Collection = chroma_client.get_or_create_collection(name="codebase_chunks")

# Fetch data and initialize BM25S natively
print("Fetching existing chunks from ChromaDB...")
all_data = collection.get()
all_docs: List[str] = all_data.get("documents", [])
all_metas: List[Dict[str, Any]] = all_data.get("metadatas", [])
all_ids: List[str] = all_data.get("ids", [])

print("Tokenizing and building bm25s index in memory...")

# We build a 'corpus' of dictionaries so we can easily retrieve the ID and metadata later
corpus = [
    {"id": doc_id, "text": text, "metadata": meta}
    for doc_id, text, meta in zip(all_ids, all_docs, all_metas)
]

# Tokenize and index using bm25s
corpus_tokens = bm25s.tokenize([doc["text"] for doc in corpus])
bm25_retriever = bm25s.BM25(corpus=corpus)
bm25_retriever.index(corpus_tokens)


class CodebaseRAG(dspy.Module):
    """Pure DSPy RAG Module"""
    def __init__(self) -> None:
        super().__init__()

        self.generate_answer = dspy.ChainOfThought(
            "context, question -> answer",
            instructions="Answer the question using the provided codebase context. Explicitly mention the file names you used from the context headers.",
        )

    def forward(self, question: str) -> dspy.Prediction:
        """
        Executes the hybrid RAG retrieval and generation pipeline for a given query.

        This method performs a dual-search strategy to find the most relevant codebase context:
        1. Semantic Search: Queries ChromaDB to find conceptually related code chunks.
        2. Keyword Search: Queries the in-memory BM25S index to find exact lexical matches.
        
        The results from both retrievers are combined, deduplicated (to prevent feeding the 
        LLM redundant tokens), and formatted with explicit file-path headers. The formatted 
        context is then passed to the LLM to generate a reasoned answer.

        Args:
            question (str): The user's technical question regarding the codebase.

        Returns:
            dspy.Prediction: A structured prediction object containing:
                - answer (str): The final response generated by the LLM.
                - reasoning (str): The step-by-step chain of thought produced by the LLM.
                - context (List[str]): The raw text chunks retrieved and used for generation.
                - sources (List[str]): A deduplicated list of file paths (e.g., 'src/main.py') 
                  that contributed to the generated answer.
        """

        # Query ChromaDB natively (Vector/Semantic Search)
        vector_results = collection.query(query_texts=[question], n_results=3)
        
        vec_docs = vector_results.get("documents", [[]])[0]
        vec_metas = vector_results.get("metadatas", [[]])[0]
        vec_ids = vector_results.get("ids", [[]])[0]

        # Query BM25S natively (Exact Keyword Search)
        query_tokens = bm25s.tokenize(question)
        # retrieve() returns a tuple of (results, scores). We take the results array.
        bm25_results, _ = bm25_retriever.retrieve(query_tokens, k=3)
        
        # Combine, rank, and deduplicate the results
        combined_chunks = []
        unique_sources: Set[str] = set()
        seen_ids: Set[str] = set()

        # Add vector results first
        for doc_id, text, meta in zip(vec_ids, vec_docs, vec_metas):
            if doc_id not in seen_ids:
                seen_ids.add(doc_id)
                source_file = meta.get("source", "Unknown file") if meta else "Unknown file"
                unique_sources.add(source_file)
                combined_chunks.append((source_file, text))

        # Add BM25S results. bm25_results[0] contains the matched dicts from our corpus.
        for match in bm25_results[0]:
            doc_id = match["id"]
            if doc_id not in seen_ids:
                seen_ids.add(doc_id)
                meta = match["metadata"]
                source_file = meta.get("source", "Unknown file") if meta else "Unknown file"
                unique_sources.add(source_file)
                combined_chunks.append((source_file, match["text"]))

        # Format context dynamically with file headers
        formatted_context_list = [
            f"--- File: {source} ---\n{text}\n" 
            for source, text in combined_chunks
        ]
        context_str = "\n".join(formatted_context_list)
        # Keep a flat list of text chunks for the final Prediction object
        context_texts = [text for _, text in combined_chunks]

        prediction = self.generate_answer(
            context=context_str, question=question
        )

        return dspy.Prediction(
            context=context_texts,
            sources=list(unique_sources),
            reasoning=getattr(prediction, "reasoning", ""),
            answer=getattr(prediction, "answer", ""),
        )

rag_bot = CodebaseRAG()

result = rag_bot(question="What does the cache module do?")

print(f"Thought Process:\n{getattr(result, 'reasoning', '')}\n")
print(f"Final Answer:\n{getattr(result, 'answer', '')}\n")

print("--- Sources Used ---")
for idx, source in enumerate(getattr(result, "sources", []), 1):
    print(f"[{idx}] {source}")